services:
  nginx-web-server:
    container_name: nginx-web-server
    image: nginx:1.26.1-alpine
    depends_on:
      - python-api
    restart: unless-stopped
    build:
      context: ./app
    networks:
      - internal-network
    ports:
      - "80:80"

  python-api:
    container_name: python-api
    image: python:3.12-alpine
    depends_on:
      - python-db-migrator
    restart: unless-stopped
    build:
      context: ./api
    networks:
      - internal-network

  postgres-db:
    container_name: postgres-db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hp_data
    restart: unless-stopped
    networks:
      - internal-network
    ports:
      - "5432:5432"

  python-db-migrator:
    container_name: python-db-migrator
    image: python:3.12
    depends_on:
      - postgres-db
    restart: no
    build:
      context: ./db
    networks:
      - internal-network

networks:
  internal-network: