services:
  webserver:
    container_name: web-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: web-server/Dockerfile
    networks:
      - internal-network
    ports:
      - "8081:80"

  python-api:
    container_name: python-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: api/Dockerfile
    networks:
      - internal-network
    ports:
      - "8082:8000"

networks:
  internal-network: