services:
  nginx-web-server:
    container_name: nginx-web-server
    depends_on:
      - python-api
    restart: unless-stopped
    build:
      context: ./app
    networks:
      - internal-network
    ports:
      - "80:80"
    healthcheck:
      test: curl --fail http://nginx-web-server
      interval: 10s
      timeout: 5s
      retries: 5

  python-api:
    container_name: python-api
    depends_on:
      - python-db-migrator
    restart: unless-stopped
    build:
      context: ./api
    networks:
      - internal-network
    healthcheck:
      test: curl --fail http://python-api
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-db:
    container_name: postgres-db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hp_data
    restart: unless-stopped
    networks:
      - internal-network
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d hp_data -U root
      interval: 10s
      timeout: 5s
      retries: 5

  python-db-migrator:
    container_name: python-db-migrator
    depends_on:
      - postgres-db
    restart: on-failure
    build:
      context: ./db
    networks:
      - internal-network

networks:
  internal-network: